### PR TITLE
Create Agnostic NFT Licence

### PR DESCRIPTION
**Pull request by Daimon-Law**
The original licence drafted for Rarible is pretty unique to that platform and doesn't lend itself to use beyond that platform. I was hoping to contribute to something the broader NFT community can use, irrespective of which platform or network they are on. In my current practice for example, the majority of my clients operate on platforms other than Ethereum and this licence should reflect that.

I've taken the liberty of mashing up a few different agreements with this and other work by @lex-node to produce something that might respond to those criteria.

As a general comment, I've got an issue with the license restrictions, the subrogation rules and risk allocation/indemnities. The original draft appears to heavily favour Rarible and its specific appetite for risk (i.e. none). My view is that if platforms are profiting from NFT trades, they need to have skin in the game, as do the Creators who are publishing works. I've never seen so much risk absorbed by those purchasing works of art in good faith at fair market price. There's something not right there so I've addressed that with some deep edits to move the risk dial back to those profiting most from the NFT - Creators along with platforms taking a cut (it's not that bad - I just expect platforms to be more accountable for their own revenue stream - after all, they can afford it). 

There will be some obvious privity issues with the license, particularly where it grant rights to sublicensees without the appropriate constraints. For example, I don't think it's reasonable to allow sublicensees (such as Rarible for example) to receive licence rights broader than those granted to Collectors themselves. That's a loophole that needs to be plugged so I've done that by way of placing obligations on licensees to ensure their sublicensees comply with the terms of the license. Really, if a Creator or Collector is going to create a sublicense, that should be done on terms "no less onerous" than those imposed on the licensees themselves.

Finally, the commercial matrix of the exclusive license needs more work - if someone is acquiring an "exclusive" licence, it would be reasonable to expect that the Collector would have the right to commercialise their ownership (and pay the premium associated with that). Without those rights, the concept of "exclusivity" rings hollow.

I haven't modified the non-exclusive licence terms yet as I'd like to understand the commercial principles being reflected in this license model. I'm hoping colleagues in the space can chime in and provide that context. Meanwhile, I hope my edits might help others trying to work through this interesting and developing area of intellectual property.

### CODE REVIEW

**Comment by lex-node** [comment]
this is great stuff, @Daimon-Law !

would you mind re-submitting the readme edits as a separate pull request? 

re: the new licenses--it sounds like they represent a very interesting but also very different approach that Rarible would have to review and consider at some length before endorsing, so it might be better off living in your own fork for now and we can open an issue pointing to it there stating that it should be reviewed for potential incorporation here in the future

**Comment by Daimon-Law** [comment]
I think you're right re: the licence - I went too far off piste so you may want to pick out any perceived improvements by exception rather than merge my version into the main.

As for the readme - you've got me here. How do I split the pull request to re-submit my readme as a separate pull request?

**Comment by lex-node** [comment]
you'd have to do some annoying stuff with rebasing 

probably simplest thing is if you fork the rarible repo (not common accord's fork of the rarible repo), paste your new readme file into the readme file on your fork, and do a pull request back into rarible repo

**Comment by Daimon-Law** [comment]
Hi Gabe - I can't fork the Rarible repo and submit a pull request as I've already submitted a pull request via the Common Accord fork I created (although I'm not sure why that happened). Any attempt to fork the Rarible repo pushes me back down under the common accord fork.

I've deleted my repo and will try again.

**Review by lex-node — APPROVED** [review]
good changes; approved

thank you!

**Comment by HazardJ** [comment]
Hi @Daimon-Law.  The kind of "forking" that you are suggesting seems well-aligned with a Prose Object approach.  That is - you would create a forked form of the agreement that consisted of the modifications and referenced the rest.  Like the "Non-Exclusive" in this use.  This is factoring and composing rather than "versioning."  There is overlap in the ideas and probably deeper integration of the two is possible, but this is a straight-forward way to allow variation while maintaining common elements.  If you have text variations, I'm happy to experiment putting them in as a variant form.  http://www.commonaccord.org/index.php?action=source&file=G/nft-license/PO/Non-Exclusive/Form/01.0.md

**Comment by Daimon-Law** [comment]
\> Hi @Daimon-Law. The kind of "forking" that you are suggesting seems well-aligned with a Prose Object approach. That is - you would create a forked form of the agreement that consisted of the modifications and referenced the rest. Like the "Non-Exclusive" in this use. This is factoring and composing rather than "versioning." There is overlap in the ideas and probably deeper integration of the two is possible, but this is a straight-forward way to allow variation while maintaining common elements. If you have text variations, I'm happy to experiment putting them in as a variant form. http://www.commonaccord.org/index.php?action=source&file=G/nft-license/PO/Non-Exclusive/Form/01.0.md

I've gone back and had a closer look at the Rarible form of licence and the more I looked the more I realised that it can't be a sound basis for licensing NFTs \_for creators\_. I've concluded that a fork or link back to the Rarible version is no longer tenable.

Now, I get that this licence is drafted for a "client" (being Rarible) and they have a specific appetite for risk and revenue aggregation. But that has huge implications for creators and collectors alike and that affects nearly every clause of the licence. 

Rarible is an intermediary only and, necessary or not, should be treated as such in any form of NFT licence. I don't know how I missed this the first time but perpetual licences don't work in the context of NFTs (and especially not to the benefit of sub-licensees). A gallery/platform could feasibly continue displaying the art long after the creator and collector have moved on. I'm sure that's unintentional so it needs to be addressed.

This brings me to the temporal issues. Intermediaries will come and go - the art embedded in NFTs won't. Does the licence stand up to the 100 year test? Does it accommodate new forms of engagement being created by artists and their audience? New ways to transact art? Does it facilitate compensation to artists and their successors for downstream trades of the NFT (as the large commercial galleries are already doing)? The only way to achieve that is to distil these agreements back to their essence.

Given the foundational concerns I have, I've decided that it might be better to go back to basics and create my own form of NFT licence catering to creators and collectors across the broad NFT diaspora, irrespective of the network they decide to use.

Thanks @lex-node for inspiring/provoking us to pull our thumbs out and create some open-source legal engineering the NFT community can use.

**Comment by HazardJ** [comment]
Hi @Daimon-Law and @lex-node 

Daimon-Law's comments make sense to me.  I won't seek to summarize them, but only to suggest that this is exactly what a "composable" system of legal text should do/permit/encourage.  Surface issues, areas of concordance and difference, etc.  My view is that there can be a common trunk for licenses - all of them whatever the subject matter - and that it can be populated in a thousand (figurative) ways.  Copyright, patent, trademark, etc. The variants on copyright, etc.  And that one license will often flow from another license.  E.g., a work of music will usually have multiple creators, and this chain is like other supply chains.  Off-the-shelf solutions would greatly reduce friction and increase transparency, even if they need some dusting or grinding to fit any particular use.  (The same kind of thinking applies to any supply chain - trade, SLAs, etc.)  I've proposed this idea in a number of places (including with Prof. Lemley)  

I've done a bunch of licenses of various types (over too many years) noodling with this idea.   
http://www.commonaccord.org/index.php?action=source&file=S/Index/License.md

I'd be thrilled to explore this notion with you, whether in the specific context of an NFT or more generally. 

This discussion is exactly the kind of thing that some of us have been hoping to have.   https://github.com/CommonAccord/NW-NDA/

Jim

**Comment by lex-node** [comment]
@Daimon-Law , all good thoughts--I'll look forward to seeing what you come up with!

**Pull request merged**
